name: POP - poutine on poutine

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/**
      - action.yml

  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/**
      - action.yml
      - '!README.md'
      - '!LICENSE'
      - '!docs/**'
      - '!.github/**'

permissions: {}

jobs:
  pop:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
    - uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        disable-sudo: true
        egress-policy: audit
        allowed-endpoints: >
          github.com:443
          api.github.com:443
          codeload.github.com:443
          objects.githubusercontent.com:443
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: boostsecurityio/poutine-action@main # Dogfood the latest action
      name: "Run poutine on poutine's own codebase"
      id: self-test
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@1b549b9259bda1cb5ddde3b41741a82a2d15a841 # v3.28.13
      with:
        sarif_file: results.sarif
